- name: "Projects"
  link: "/projects"
- name: "About"
  link: "/about"
- name: "Design"
  link: "/design"
- name: "Photography"
  link: "/photography"
- name: "Illustration"
  link: "/illustration"